/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayersSMPOW = {}

var UnminedPlayersSMPNether = {}

var UnminedPlayersSMPEnd = {}

var UnminedPlayersCMPOW = {}

var mapPlayersArray = [UnminedPlayersSMPOW, UnminedPlayersSMPNether, UnminedPlayersSMPEnd, UnminedPlayersCMPOW]
