/* Autogenerated file created by UpdateSMPViewer.py */
/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers_CMP_END = {}

/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers_CMP_NETHER = {}

/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers_CMP_OVERWORLD = {}

/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers_SMP_OVERWORLD = {}

var mapPlayersArray = [UnminedPlayers_SMP_OVERWORLD, UnminedPlayers_CMP_OVERWORLD, UnminedPlayers_CMP_NETHER, UnminedPlayers_CMP_END];
